#!/usr/bin/env sh
# Alpacca installer (Linux / macOS) — fully offline once the repo is on disk.
#
# Alpacca is pure Python with zero dependencies, so "installing" just means
# putting an `alpacca` launcher on your PATH that runs this checkout.
# Nothing is downloaded, compiled, or fetched from any package index.
#
#   scripts/install.sh             # installs launcher to ~/.local/bin
#   PREFIX=/usr/local scripts/install.sh
#   NO_MODIFY_PATH=1 scripts/install.sh   # don't touch shell rc files
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
prefix=${PREFIX:-"$HOME/.local"}
bin_dir="$prefix/bin"

python=$(command -v python3 || command -v python) || {
    echo "error: python3 (>= 3.10) is required" >&2
    exit 1
}
"$python" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' || {
    echo "error: python >= 3.10 is required (found $("$python" -V))" >&2
    exit 1
}

mkdir -p "$bin_dir"
cat > "$bin_dir/alpacca" <<EOF
#!/usr/bin/env sh
# launcher generated by alpacca's install.sh — runs the checkout at:
#   $repo_root
exec env PYTHONPATH="$repo_root\${PYTHONPATH:+:\$PYTHONPATH}" "$python" -m alpacca "\$@"
EOF
chmod +x "$bin_dir/alpacca"
echo "installed launcher: $bin_dir/alpacca -> $repo_root"

case ":$PATH:" in
    *":$bin_dir:"*) on_path=1 ;;
    *)              on_path=0 ;;
esac
if [ "$on_path" -eq 0 ] && [ -z "${NO_MODIFY_PATH:-}" ]; then
    path_line="export PATH=\"$bin_dir:\$PATH\""
    updated=""
    for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
        [ -f "$rc" ] || continue
        grep -qF "$path_line" "$rc" 2>/dev/null && continue
        printf '\n# added by the alpacca installer\n%s\n' "$path_line" >> "$rc"
        updated="$updated $rc"
    done
    if [ -n "$updated" ]; then
        echo "added $bin_dir to PATH in:$updated"
    else
        echo "add this to your shell profile to finish:"
        echo "  $path_line"
    fi
fi

echo
echo "done. open a NEW terminal and try:"
echo "  alpacca doctor"
echo "  alpacca run llama3.2:1b \"hello!\""
echo
echo "optional speed-up (the only thing that would ever touch a package index):"
echo "  $python -m pip install numpy"
