# Alpacca installer (Windows / PowerShell) - fully offline once the repo
# is on disk. Alpacca is pure Python with zero dependencies, so installing
# just means creating an `alpacca` launcher on your user PATH that runs
# this checkout. Nothing is downloaded or compiled.
#
#   .\scripts\install.ps1
#   $env:ALPACCA_PREFIX = "D:\tools\alpacca"; .\scripts\install.ps1

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Prefix   = if ($env:ALPACCA_PREFIX) { $env:ALPACCA_PREFIX } else { Join-Path $env:LOCALAPPDATA "Alpacca" }
$BinDir   = Join-Path $Prefix "bin"

$py = Get-Command python -ErrorAction SilentlyContinue
if (-not $py) { $py = Get-Command python3 -ErrorAction SilentlyContinue }
if (-not $py) {
    Write-Error "python (>= 3.10) is required - install it from python.org or 'winget install Python.Python.3.12'"
}
& $py.Source -c "import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)"
if ($LASTEXITCODE -ne 0) { Write-Error "python >= 3.10 is required" }

New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$launcher = Join-Path $BinDir "alpacca.cmd"
@"
@echo off
rem launcher generated by alpacca's install.ps1 - runs the checkout at:
rem   $RepoRoot
setlocal EnableExtensions
set "PYTHONUTF8=1"
set "PYTHONPATH=$RepoRoot;%PYTHONPATH%"
"$($py.Source)" -m alpacca %*
"@ | Set-Content -Path $launcher -Encoding ascii
Write-Host "installed launcher: $launcher -> $RepoRoot"

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if (-not $userPath) { $userPath = "" }
if (($userPath -split ";") -notcontains $BinDir) {
    [Environment]::SetEnvironmentVariable("Path", ($userPath.TrimEnd(";") + ";" + $BinDir), "User")
    Write-Host "added $BinDir to your user PATH"
}

Write-Host ""
Write-Host "done. open a NEW terminal (PowerShell or cmd) and try:"
Write-Host "  alpacca"
Write-Host "  alpacca doctor"
Write-Host "  alpacca run llama3.2:1b `"hello!`""
Write-Host ""
Write-Host "optional speed-ups (the only things that would ever touch a package index):"
Write-Host "  python -m pip install numpy"
Write-Host "  cd `"$RepoRoot`""
Write-Host "  python -m pip install `".[kernels]`""
